### Numpy library

In [2]:
import numpy as np

#creating 1 D array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

In [ ]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)  # 2 rows and 5 columns

In [ ]:
np.arange(0,10,2).reshape(5,1) # just like range function in python and reshapes it to 5 rows and 1 column

In [14]:
np.ones((3,4)) # creates 3 rows and 4 columns with all values as 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
#identity matrix
np.eye(3) # 3x3 matrix with diagonal values as 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr=np.random.rand(5,5) # 5x5 matrix with random values between 0 and 1
print(arr)

[[0.00441602 0.57816186 0.7948685  0.85497564 0.23426585]
 [0.89735648 0.39962578 0.53379799 0.74887374 0.058207  ]
 [0.49668466 0.84955468 0.59872704 0.08431032 0.19962834]
 [0.71933922 0.72498821 0.4096832  0.03556313 0.50972927]
 [0.70977796 0.13271036 0.31471964 0.78003663 0.78340339]]


In [22]:
#Attributes of numpy arrays
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Array",arr)
print("Shape: ",arr.shape)
print("Size: ",arr.size)
print("Number of dimensions: ",arr.ndim)
print("Data type: ",arr.dtype)
print("Item size:(in bytes) ",arr.itemsize)

Array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape:  (2, 5)
Size:  10
Number of dimensions:  2
Data type:  int64
Item size:(in bytes)  8


In [ ]:
#Numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

#Element wise addition
print("Addition: ",arr1+arr2)
#Element wise subtraction
print("Subtraction: ",arr1-arr2)
#Element wise multiplication
print("Multiplication: ",arr1*arr2)
#Element wise division
print("Division: ",arr1/arr2)


Addition:  [ 7  9 11 13 15]
Subtraction:  [-5 -5 -5 -5 -5]
Multiplication:  [ 6 14 24 36 50]
Division:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [28]:
#Universl functions

arr=np.array([1,2,3,4,5])

#Square root
print("Square root: ",np.sqrt(arr))
#Exponential
print("Exponential: ",np.exp(arr))
#Sine
print("Sine: ",np.sin(arr))
#Cosine
print("Cosine: ",np.cos(arr))
#Log
print("Log: ",np.log(arr))

Square root:  [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Log:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [20]:
#Indexing and slicing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print("Array: ",arr)
# print("Element at 0th row and 0th column: ",arr[0,0])
# print("Element at 1st row and 2nd column: ",arr[1,2])
# print("Elements from 0th row and 0th column to 1st row and 2nd column: ",arr[0:2,0:3])
# print(arr[1:3,0:3]) # 1st row
# print(arr.flatten()) # converts 2D array to 1D array
# print(arr.ravel()) # converts 2D array to 1D array
# print(arr)
# print(arr.argmax())#index of maximum element
# print(arr.argmin())#index of minimum element

print(arr.sum())#sum of all elements


Array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
120


In [21]:
data=np.array([1,2,3,4,5])

avg=data.mean()
print("Mean: ",avg)

standard_deviation=data.std()
print("Standard deviation: ",standard_deviation)

variance=data.var()
print("Variance: ",variance)

# #Reshaping
# arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# print("Original array: ",arr)
# print("Reshaped array: ",arr.reshape(5,2))

Mean:  3.0
Standard deviation:  1.4142135623730951
Variance:  2.0
Original array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reshaped array:  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
